### PR TITLE
Cause exit status 1 when there are test failures

### PR DESCRIPTION
**Pull request by rrosenblum**
We have CukeForker wired up to a Jenkins build. Whenever there is a failure in the CukeForker runner, our build shows as green instead of red because CukeForker will exit with a status code of 0. This change will cause the exit status to be 1 if there are any test failures.

### CODE REVIEW

**Comment by jarib** [comment]
Thanks!

Since it's possible to use cukeforker as a library (i.e. use your own wrapper instead of the gem's executable), I think it would make more sense to make `CukeForker::Runner#run` return a status symbol (e.g. `:success` or `:failure`) and move the actual `exit` call to `bin/cukeforker`.

That way we'll get the correct exit code without forcing the exit on people who don't use the executable. 

What do you think?

**Comment by rrosenblum** [comment]
I think that makes a lot of sense. To be honest with you, I am not too familiar with all of the use cases of CukeForker. One of the automation engineers ran into the exit status issue and stepped in to help him out. With our usage of CukeForker being inside of a rake task, it made sense for me at the time to issue `exit 1`. 

What do you think of having `CukeForker::Runner#run` return `true` if all tests pass and `false` if any tests fail? That way a user can simply check a boolean status instead of having to check against a symbol status that could potentially change.

I will look into making the changes discussed.

**Comment by rrosenblum** [comment]
I think that makes a lot of sense. To be honest with you, I am not too familiar with all of the use cases of CukeForker. One of the automation engineers ran into the exit status issue and stepped in to help him out. With our usage of CukeForker being inside of a rake task, it made sense for me at the time to issue `exit 1`. 

What do you think of having `CukeForker::Runner#run` return `true` if all tests pass and `false` if any tests fail? That way a user can simply check a boolean status instead of having to check against a symbol status that could potentially change.

I will look into making the changes discussed.

**Comment by rrosenblum** [comment]
I have made some updates to the code, let me know what you think of the changes.

**Comment by jarib** [comment]
I was thinking a "status" symbol would make sense since that would leave us the option of having more than one failure state in the future. Using a boolean removes that option. Not really a big deal though. WDYT?

**Comment by rrosenblum** [comment]
I like having the option to handle multiple statuses in code. I am not sure how much a user is going to want to have to wire up checking for multiple statuses. The nice thing about a boolean is that it is very simplistic. 

Aside from `:success` and `:failure`, did you have any other statuses in mind?

When it comes down to it, I am fine implementing the return as a symbol or a boolean.

**Comment by rrosenblum** [comment]
I added the functionality to create a `CukeForker` rake tasks. I know that this is out of place from the other commit, but it is a piece of functionality that I would like to add in after we iron the exit status. I will gladly move it to a different branch if need be.

**Comment by jarib** [comment]
OK, let's stick with the boolean.

**Comment by jarib** [comment]
Released as 0.2.5

**Comment by jchristi** [comment]
@rrosenblum I use CukeForker with Jenkins as well. I use the [Log Parser plugin](https://wiki.jenkins-ci.org/display/JENKINS/Log+Parser+Plugin) to set failure status in Jenkins. It certainly is a bit more hackish but it works without modifying CukeForker.

**Pull request merged**
